version: '3'

services:
  inbucket:
    image: inbucket/inbucket
    container_name: inbucket-compose
    ports:
      - "9001:9000"
      - "25:2500"
      - "110:1100"
    restart: unless-stopped

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   depends_on:
  #     - inbucket
  #   restart: unless-stopped

networks:
  default:
    driver: bridge
